name: object-IR
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - _anaconda_depends=2020.07=py38_0
  - _ipyw_jlab_nb_ext_conf=0.1.0=py38_0
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=2.1.0=pyhd8ed1ab_0
  - aiohttp=3.7.3=py38h25fe258_0
  - alabaster=0.7.12=py_0
  - anaconda=custom=py38_1
  - anaconda-client=1.7.2=py38_0
  - anaconda-navigator=1.10.0=py38_0
  - anaconda-project=0.8.4=py_0
  - argh=0.26.2=py38_0
  - argon2-cffi=20.1.0=py38h7b6447c_1
  - asn1crypto=1.4.0=py_0
  - astroid=2.4.2=py38_0
  - astropy=4.0.2=py38h7b6447c_0
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - atomicwrites=1.4.0=py_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - autopep8=1.5.4=py_0
  - babel=2.8.1=pyhd3eb1b0_0
  - backcall=0.2.0=py_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - backports.shutil_get_terminal_size=1.0.0=py38_2
  - backports.tempfile=1.0=py_1
  - backports.weakref=1.0.post1=py_1
  - beautifulsoup4=4.9.3=pyhb0f4dca_0
  - bitarray=1.6.1=py38h27cfd23_0
  - bkcharts=0.2=py38_0
  - blas=1.0=mkl
  - bleach=3.2.1=py_0
  - blinker=1.8.2=pyhd8ed1ab_0
  - blosc=1.20.1=hd408876_0
  - bokeh=2.2.3=py38_0
  - boto=2.49.0=py38_0
  - bottleneck=1.3.2=py38heb32a55_1
  - brotlipy=0.7.0=py38h7b6447c_1000
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h36c2ea0_0
  - ca-certificates=2025.1.31=hbcca054_0
  - cachetools=4.2.4=pyhd8ed1ab_0
  - cairo=1.14.12=h8948797_3
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.14.3=py38he30daa8_0
  - chardet=3.0.4=py38_1003
  - cloudpickle=1.6.0=py_0
  - clyent=1.2.2=py38_1
  - colorama=0.4.4=py_0
  - conda=22.9.0=py38h06a4308_0
  - conda-package-handling=1.7.2=py38h03888b9_0
  - conda-verify=3.4.2=py_1
  - contextlib2=0.6.0.post1=py_0
  - cryptography=3.1.1=py38h1ba5d50_0
  - cudatoolkit=11.0.221=h6bb024c_0
  - curl=7.71.1=hbc83047_1
  - cycler=0.10.0=py38_0
  - cython=0.29.21=py38he6710b0_0
  - cytoolz=0.11.0=py38h7b6447c_0
  - dask=2.30.0=py_0
  - dask-core=2.30.0=py_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - diff-match-patch=20200713=py_0
  - distributed=2.30.1=py38h06a4308_0
  - docutils=0.16=py38_1
  - einops=0.7.0=pyhd8ed1ab_1
  - entrypoints=0.3=py38_0
  - et_xmlfile=1.0.1=py_1001
  - expat=2.2.10=he6710b0_2
  - fastcache=1.1.0=py38h7b6447c_0
  - flake8=3.8.4=py_0
  - flask=1.1.2=py_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.4=h5ab3b9f_0
  - fribidi=1.0.10=h7b6447c_0
  - future=0.18.2=py38_1
  - get_terminal_size=1.0.0=haa9412d_0
  - gevent=20.9.0=py38h7b6447c_0
  - glib=2.66.1=h92f7085_0
  - glob2=0.7=py_0
  - gmp=6.1.2=h6c8ec71_1
  - gmpy2=2.0.8=py38hd5f6e3b_3
  - graphite2=1.3.14=h23475e2_0
  - greenlet=0.4.17=py38h7b6447c_0
  - grpcio=1.33.2=py38heead2fc_2
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - harfbuzz=2.4.0=hca77d97_1
  - hdf5=1.10.4=hb1b8bf9_0
  - heapdict=1.0.1=py_0
  - html5lib=1.1=py_0
  - icu=58.2=he6710b0_3
  - idna=2.10=py_0
  - imageio=2.9.0=py_0
  - imagesize=1.2.0=py_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - iniconfig=1.1.1=py_0
  - intel-openmp=2020.2=254
  - intervaltree=3.1.0=py_0
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.19.0=py38hb070fc8_0
  - ipython_genutils=0.2.0=py38_0
  - ipywidgets=7.5.1=py_1
  - isort=5.6.4=py_0
  - itsdangerous=1.1.0=py_0
  - jbig=2.1=hdba287a_0
  - jdcal=1.4.1=py_0
  - jedi=0.17.1=py38_0
  - jeepney=0.5.0=pyhd3eb1b0_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.5=py_0
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py38_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.6.3=py38_0
  - jupyterlab=2.2.6=py_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=1.2.0=py_0
  - keyring=21.4.0=py38_1
  - kiwisolver=1.3.0=py38h2531618_0
  - krb5=1.18.2=h173b8e3_0
  - lazy-object-proxy=1.4.3=py38h7b6447c_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libarchive=3.4.2=h62408e4_0
  - libcurl=7.71.1=h20c2e04_1
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgomp=11.2.0=h1234567_1
  - liblief=0.10.1=he6710b0_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libllvm9=9.0.1=h4a3c616_1
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.13.0.1=h8b12597_0
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=he6710b0_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libtool=2.4.6=h7b6447c_1005
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - libxslt=1.1.34=hc22bd24_0
  - llvmlite=0.34.0=py38h269e1b5_4
  - locket=0.2.0=py38_1
  - lxml=4.6.1=py38hefd8a0e_0
  - lz4-c=1.9.2=heb0550a_3
  - lzo=2.10=h7b6447c_2
  - markdown=3.3.4=pyhd8ed1ab_0
  - markupsafe=1.1.1=py38h7b6447c_0
  - mccabe=0.6.1=py38_1
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.2.0=py38h23d657b_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - mock=4.0.2=py_0
  - more-itertools=8.6.0=pyhd3eb1b0_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.1.0=py38_0
  - msgpack-python=1.0.0=py38hfd86e86_1
  - multidict=4.7.5=py38h1e0a361_2
  - multipledispatch=0.6.0=py38_0
  - navigator-updater=0.2.1=py38_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py38_0
  - nbformat=5.0.8=py_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.2=pyhd3eb1b0_0
  - networkx=2.5=py_0
  - ninja=1.10.2=hff7bd54_1
  - nltk=3.5=py_0
  - nose=1.3.7=py38_2
  - notebook=6.1.4=py38_0
  - numba=0.51.2=py38h0573a6f_1
  - numexpr=2.7.1=py38h423224d_0
  - numpydoc=1.1.0=pyhd3eb1b0_1
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - olefile=0.46=py_0
  - openpyxl=3.0.5=py_0
  - openssl=1.1.1k=h27cfd23_0
  - pandoc=2.11=hb0f4dca_0
  - pandocfilters=1.4.3=py38h06a4308_1
  - pango=1.45.3=hd140c19_0
  - parso=0.7.0=py_0
  - partd=1.1.0=py_0
  - patchelf=0.12=he6710b0_0
  - path=15.0.0=py38_0
  - path.py=12.5.0=0
  - pathlib2=2.3.5=py38_0
  - pathtools=0.1.2=py_1
  - patsy=0.5.1=py38_0
  - pcre=8.44=he6710b0_0
  - pep8=1.7.1=py38_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=8.2.0=py38he98fc37_0
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.40.0=h7b6447c_0
  - pkginfo=1.6.1=py38h06a4308_0
  - pluggy=0.13.1=py38_0
  - ply=3.11=py38_0
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.8=py_0
  - prompt_toolkit=3.0.8=0
  - ptyprocess=0.6.0=py38_0
  - py=1.9.0=py_0
  - py-lief=0.10.1=py38h403a769_0
  - pyasn1=0.6.1=pyhd8ed1ab_1
  - pyasn1-modules=0.4.1=pyhd8ed1ab_0
  - pycodestyle=2.6.0=py_0
  - pycosat=0.6.3=py38h7b6447c_1
  - pycparser=2.20=py_2
  - pycurl=7.43.0.6=py38h1ba5d50_0
  - pydocstyle=5.1.1=py_0
  - pyflakes=2.2.0=py_0
  - pygments=2.7.2=pyhd3eb1b0_0
  - pyjwt=2.0.1=pyhd8ed1ab_0
  - pylint=2.6.0=py38_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.17.3=py38h7b6447c_0
  - pysocks=1.7.1=py38_0
  - pytables=3.6.1=py38h9fd0a39_0
  - pytest=6.1.1=py38_0
  - python=3.8.5=h7579374_1
  - python-jsonrpc-server=0.4.0=py_0
  - python-language-server=0.35.1=py_0
  - python-libarchive-c=2.9=py_0
  - python_abi=3.8=2_cp38
  - pytz=2020.1=py_0
  - pywavelets=1.1.1=py38h7b6447c_2
  - pyxdg=0.27=pyhd3eb1b0_0
  - pyyaml=5.3.1=py38h7b6447c_1
  - pyzmq=19.0.2=py38he6710b0_1
  - qdarkstyle=2.8.1=py_0
  - qt=5.9.7=h5867ecd_1
  - qtawesome=1.0.1=py_0
  - qtconsole=4.7.7=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h7b6447c_0
  - regex=2020.10.15=py38h7b6447c_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_0
  - ripgrep=12.1.1=0
  - rope=0.18.0=py_0
  - rsa=4.9=pyhd8ed1ab_0
  - rtree=0.9.4=py38_1
  - ruamel_yaml=0.15.87=py38h7b6447c_1
  - scikit-image=0.19.2=py38h51133e4_0
  - scikit-learn=0.23.2=py38h0573a6f_0
  - seaborn=0.11.0=py_0
  - secretstorage=3.1.2=py38_0
  - send2trash=1.5.0=py38_0
  - setuptools=50.3.1=py38h06a4308_1
  - simplegeneric=0.8.1=py38_2
  - singledispatch=3.4.0.3=py_1001
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=py38h06a4308_0
  - snappy=1.1.8=he6710b0_0
  - snowballstemmer=2.0.0=py_0
  - sortedcollections=1.2.1=py_0
  - sortedcontainers=2.2.2=py_0
  - soupsieve=2.0.1=py_0
  - sphinx=3.2.1=py_0
  - sphinxcontrib=1.0=py38_1
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sphinxcontrib-websupport=1.2.4=py_0
  - spyder=4.1.5=py38_0
  - spyder-kernels=1.9.4=py38_0
  - sqlalchemy=1.3.20=py38h7b6447c_0
  - sqlite=3.33.0=h62c20be_0
  - statsmodels=0.12.0=py38h7b6447c_0
  - sympy=1.6.2=py38h06a4308_1
  - tbb=2020.3=hfd86e86_0
  - tblib=1.7.0=py_0
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - terminado=0.9.1=py38_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tifffile=2020.10.1=py38hdd07704_2
  - tk=8.6.10=hbc83047_0
  - toml=0.10.1=py_0
  - toolz=0.11.1=py_0
  - tornado=6.0.4=py38h7b6447c_1
  - traitlets=5.0.5=py_0
  - ujson=4.0.1=py38he6710b0_0
  - unicodecsv=0.14.1=py38_0
  - unixodbc=2.3.9=h7b6447c_0
  - urllib3=1.25.11=py_0
  - watchdog=0.10.3=py38_0
  - webencodings=0.5.1=py38_1
  - werkzeug=1.0.1=py_0
  - wheel=0.35.1=py_0
  - widgetsnbextension=3.5.1=py38_0
  - wrapt=1.11.2=py38h7b6447c_0
  - wurlitzer=2.0.1=py38_0
  - xlrd=1.2.0=py_0
  - xlsxwriter=1.3.7=py_0
  - xlwt=1.3.0=py38_0
  - xmltodict=0.12.0=py_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.30.0=py_0
  - yarl=1.6.3=py38h25fe258_0
  - zeromq=4.3.3=he6710b0_3
  - zict=2.0.0=py_0
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zope=1.0=py38_1
  - zope.event=4.5.0=py38_0
  - zope.interface=5.1.2=py38h7b6447c_0
  - zstd=1.4.5=h9ceee32_0
  - pip:
      - accelerate==1.0.1
      - addict==2.4.0
      - asttokens==3.0.0
      - bitsandbytes==0.45.5
      - cfgv==3.4.0
      - charset-normalizer==3.4.3
      - click==8.1.8
      - contourpy==1.1.1
      - datasets==3.1.0
      - dill==0.3.8
      - distlib==0.4.0
      - dists-pytorch==0.1
      - executing==2.2.0
      - facexlib==0.3.0
      - ffmpeg-python==0.2.0
      - filelock==3.16.1
      - filterpy==1.4.5
      - fonttools==4.57.0
      - fsspec==2024.9.0
      - ftfy==6.2.3
      - google-auth==2.40.1
      - google-auth-oauthlib==1.0.0
      - h5py==3.7.0
      - hdbscan==0.8.40
      - huggingface-hub==0.26.5
      - icecream==2.1.5
      - identify==2.6.1
      - imageio-ffmpeg==0.5.1
      - importlib-resources==6.4.5
      - joblib==1.4.2
      - lmdb==1.7.3
      - matplotlib==3.7.5
      - moviepy==1.0.3
      - multiprocess==0.70.16
      - nodeenv==1.9.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.1.105
      - openai-clip==1.0.1
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.12.0.88
      - packaging==24.2
      - pandas==2.0.3
      - piq==0.8.0
      - platformdirs==4.3.6
      - pre-commit==3.5.0
      - proglog==0.1.12
      - protobuf==4.25.7
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==17.0.0
      - pyiqa==0.1.14.1
      - pyodbc==4.0.30
      - python-dateutil==2.9.0.post0
      - requests==2.32.4
      - ruff==0.12.8
      - safetensors==0.4.5
      - scipy==1.10.1
      - sentencepiece==0.2.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.1
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - timm==1.0.12
      - tokenizers==0.15.2
      - torch==2.4.1
      - torch-cluster==1.6.3+pt24cu121
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt24cu121
      - torch-sparse==0.6.18+pt24cu121
      - torch-spline-conv==1.2.2+pt24cu121
      - torchvision==0.19.1
      - tqdm==4.67.1
      - transformers==4.37.2
      - triton==3.0.0
      - typing-extensions==4.5.0
      - tzdata==2024.2
      - ultralytics==8.3.43
      - ultralytics-thop==2.0.12
      - virtualenv==20.33.1
      - wcwidth==0.2.13
      - xxhash==3.5.0
prefix: /mnt/anaconda3/envs/object-IR
